### ISSUE TITLE
JsonDecodeError

### ISSUE THREAD

**Issue by edfolmi** [cletusola/rapidTicket#1]
I am getting JsonDecodeError whenever is about to save after a successful payment

**Comment by cletusola** [comment]
I think this explains the issue and a potential solution. 

https://stackoverflow.com/questions/50651232/jsondecodeerror-django

**Comment by edfolmi** [comment]
I've found a way out, but i haven't decode anything. I just verified then the payment then got the JSON as .text... Acknowledge!

**Comment by cletusola** [comment]
Sounds good .
